version: '3'

services:
  angular:
    container_name: angular
    image: diogomfernandes/scheduling-optimizer-ui
    ports:
      - 3000:80
    networks:
      - scheduling-optimizer
  backend:
    container_name: backend
    image: henriquepcabral/scheduling-optimizer-api
    ports:
      - 3080:8080
    networks:
      - scheduling-optimizer

networks:
  scheduling-optimizer:
    driver: bridge